### Find ALl Movies
GET http://localhost:8080/api/movies

### Find Movie By ID
GET http://localhost:8080/api/movies/2


### Create new Movie
POST http://localhost:8080/api/movies
Content-Type: application/json

{
  "id": 11,
  "title": "Time Rift",
  "releaseDate": "2024-04-12T00:00:00",
  "prodCompany": "Temporal Journeys Ltd.",
  "review": 88,
  "rating": "PG-13",
  "url": "https://www.timeriftmovie.com"
}

### Create new Movie with empty titles
POST http://localhost:8080/api/movies
Content-Type: application/json

{
  "id": 12,
  "title": ,
  "releaseDate": "2023-09-29T00:00:00",
  "prodCompany": "CyberDream Productions",
  "review": 81,
  "rating": "R",
  "url": "https://www.neonnexusfilm.com"
}

### Update an existing Movie
PUT http://localhost:8080/api/movies/11
Content-Type: application/json

{
  "id": 11,
  "title": "Time Rift!!!",
  "releaseDate": "2024-04-12T00:00:00",
  "prodCompany": "Temporal Journeys Ltd.",
  "review": 100,
  "rating": "PG-13",
  "url": "https://www.timeriftmovie.com"
}

### Delete a Run
DELETE http://localhost:8080/api/movies/11

